#Example: Default, Redstone
Balancer-Implementation: Redstone

#Server needs to be apart of both groups to be considered a hub server.
Redstone-Groups:
  - "DEV"
  - "Lobby"

#TODO
Donator-Hub: hub-restricted

#This bit is not needed if you are using the Redstone Implementation.
Hub-Servers:
  - hub-01
  - hub-02